// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twpwxretpytbuksboyfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3cHd4cmV0cHl0YnVrc2JveWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5OTg5MTUsImV4cCI6MjA2NzU3NDkxNX0.iycN9hyqmpQe3TEUgd0zGPbxvRp2VBZiaplp3RURekw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});